name: Post coverage comment

# Note: this only runs when the workflow exists on the master branch, so will have to debug this after the initial
# release
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  coverage:
    name: Generate Coverage Comments
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317 # v4
        id: download
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@7188638f871f721a365d644f505d1ff3df20d683 # v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          MERGE_COVERAGE_FILES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt